name: pull-DM-catalogue
on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches:
      - main
    paths:
      - science/blacklist.json
      - science/api.js
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ½ï¸ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Gets latest DM catalogue
        run: node api.js
      - name: ğŸš€ Commit and push if it changed
        run: |
          git config user.name "Zach Manson"
          git config user.email "zachpmanson@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update data: ${timestamp}" || exit 0
          git push
